model:
  name: 'AlexNet'
  params:
    in_channels: 1
    out_channels: 10
    pretrained: False

optimizer:
  name: 'adam'
  params:
    lr: 0.0001

scheduler:
  name: 'step'
  params:
    step_size: 5

loss:
  name: 'CrossEntropy'

transforms:
  exist: False
  train:
    name: 'Trans'
    params:
      train: True
  test:
    name: 'Trans'
    params:
      train: False

data:
  path: './input/fashionmnist/df.csv'
  store: None
  val_fold: 1
  train_bs: 64
  val_bs: 64
  nb_epochs: 100

dataset:
  name: 'FMNIST'

output:
  path: './out/example-FMNIST/AlexNet/'
  name: ''
