model:
  name: 'ResNet'
  params:
    in_channels: 1
    out_channels: 2
    pretrained: False

optimizer:
  name: 'adam'
  params:
    lr: 0.0001

scheduler:
  name: 'step'
  params:
    step_size: 5

metric:
  name: 'MultiClassificationMeter'
  params: None

loss:
  name: 'CrossEntropy'

data:
  path: './data/image-split/split.csv'
  store: './data/image-split/'
  val_fold: 1
  train_bs: 64
  val_bs: 64
  nb_epochs: 20

output:
  path: 'out/image-classification/res4/'
  name: ''
